name: 生成TWRP设备树

on:
  workflow_dispatch:
    inputs:
      PY:
        description: 'Python3版本（推荐3.6/3.9）'
        required: true
        default: '3.9'
      IMG:
        description: 'IMG直链'
        required: true
        default: 'https://120-232-77-34.pd1.123pan.cn:30443/download-cdn.123pan.cn/123-781/5ff8c6f1/1817957955-0/5ff8c6f12d42ea2d9e4e64b41aafdf0d/c-m17?v=5&t=1715433363&s=1715433363dd3f6d3a48537ce9f7a9508302a42805&r=FSVTRO&bzc=2&bzs=313831333534353630323a32393434303630333a33333535343433323a31383133353435363032&filename=recovery_nopatch_PDBM00.bin&x-mf-biz-cid=274431e6-ec9a-4d28-b02a-62b2e7cf6728-584000&auto_redirect=0&ndcp=1&cache_type=1&xmfcid=1b288bed-e8f7-40e6-9f27-70dea278c1ae-0-9eed82220'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: 准备环境
        run: |
          sudo apt update
          sudo apt -y install cpio wget

      - name: 准备Python3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.PY }}
          cache: 'pip'
          
      - name: 准备twrpdtgen
        run: pip3 install -r requirements.txt
        
      - name: 下载
        run: wget ${{ github.event.inputs.IMG }}
        
      - name: 跑
        run: |
          mkdir out
          python3 -m twrpdtgen -o ./out/ *.img
          
      - name: 打压缩包
        run: |
          cd ./out
          zip -r -9 DeviceTree.zip ./*
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/DeviceTree.zip
          name: TWRP_Device_Tree-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: DeviceTree 4 TWRP
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
